/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames;

import GestionBancaire.ConnectionBD;
import MyFrames.MyPanels.NouveauComptePanel;
import MyFrames.MyPanels.SupprimerComptePanel;
import MyFrames.MyPanels.OpérationComptePanel;
import MyFrames.MyPanels.VisionnerOpérationsPanel;
import gestionbancaire3.Authentification;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.PrintWriter;
import java.sql.ResultSet;

/**
 *
 * @author asus pro
 */
public class FrameCompte extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameCompte
     */
    GridBagLayout layout = new GridBagLayout();
    NouveauComptePanel nouveauComptePanel;
    SupprimerComptePanel supprimerComptePanel;
    VisionnerOpérationsPanel visionnerOpérationsPanel;
    OpérationComptePanel opérationComptePanel;
    
    private static FrameCompte myInstance;

    public static FrameCompte getInstance() {
        if (myInstance == null) {
            myInstance = new FrameCompte();
        }
        return myInstance;
    }
    public FrameCompte() {
        initComponents();
        nouveauComptePanel = new NouveauComptePanel();
        supprimerComptePanel = new SupprimerComptePanel();
        visionnerOpérationsPanel = new VisionnerOpérationsPanel();
        opérationComptePanel =  new OpérationComptePanel();
        DynamicPanel.setLayout(layout);
        
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(nouveauComptePanel,c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(supprimerComptePanel,c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(visionnerOpérationsPanel,c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(opérationComptePanel,c);
     
        afficherPanelNouveauCompte();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sideBarMenuPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnOpérations = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Compte");
        setMinimumSize(new java.awt.Dimension(80, 34));
        setNormalBounds(new java.awt.Rectangle(0, 0, 80, 0));
        setPreferredSize(new java.awt.Dimension(713, 377));
        setVisible(false);

        sideBarMenuPanel.setBackground(new java.awt.Color(153, 153, 255));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jButton1.setText("Nouveau");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnOpérations.setBackground(new java.awt.Color(0, 153, 153));
        btnOpérations.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        btnOpérations.setText("Liste Opération");
        btnOpérations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpérationsActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jButton3.setText("Opérations");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarMenuPanelLayout = new javax.swing.GroupLayout(sideBarMenuPanel);
        sideBarMenuPanel.setLayout(sideBarMenuPanelLayout);
        sideBarMenuPanelLayout.setHorizontalGroup(
            sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpérations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sideBarMenuPanelLayout.setVerticalGroup(
            sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarMenuPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton1)
                .addGap(58, 58, 58)
                .addComponent(jButton3)
                .addGap(61, 61, 61)
                .addComponent(jButton4)
                .addGap(70, 70, 70)
                .addComponent(btnOpérations)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(sideBarMenuPanel, java.awt.BorderLayout.LINE_START);

        DynamicPanel.setMaximumSize(new java.awt.Dimension(85, 23));
        DynamicPanel.setMinimumSize(new java.awt.Dimension(85, 23));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       afficherPanelSuppressionCompte();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       afficherPanelNouveauCompte();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnOpérationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpérationsActionPerformed
      afficherPanelOpérationsTable();
    }//GEN-LAST:event_btnOpérationsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         afficherPanelOpérations();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void afficherPanelSuppressionCompte()
    {
        nouveauComptePanel.setVisible(false);
        supprimerComptePanel.setVisible(true);
        visionnerOpérationsPanel.setVisible(false);
        opérationComptePanel.setVisible(false);
        
    }
    
    public void afficherPanelNouveauCompte()
    {
        nouveauComptePanel.setVisible(true);
        supprimerComptePanel.setVisible(false);
        visionnerOpérationsPanel.setVisible(false);
        opérationComptePanel.setVisible(false);
    }
    
    public void afficherPanelOpérationsTable()
    {
        nouveauComptePanel.setVisible(false);
        supprimerComptePanel.setVisible(false);
        visionnerOpérationsPanel.setVisible(true);
        opérationComptePanel.setVisible(false);
    }
    
    public void afficherPanelOpérations()
    {
        nouveauComptePanel.setVisible(false);
        supprimerComptePanel.setVisible(false);
        visionnerOpérationsPanel.setVisible(false);
        opérationComptePanel.setVisible(true);   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton btnOpérations;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel sideBarMenuPanel;
    // End of variables declaration//GEN-END:variables

  
    
}
