/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames;

import GestionBancaire.ConnectionBD;


import MyFrames.MyPanels.ModificationEmployéPanel;

import MyFrames.MyPanels.NouveauEmployéPanel;

import MyFrames.MyPanels.SuppressionEmployéPanel;
import MyFrames.MyPanels.VisionnerEmployéPanel;

import static MyFrames.MyPanels.VisionnerEmployéPanel.fillTable;
import gestionbancaire3.Authentification;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.ResultSet;

/**
 *
 * @author asus pro
 */
public class FrameEmployé extends javax.swing.JInternalFrame {

    GridBagLayout layout = new GridBagLayout();
    public static NouveauEmployéPanel nouveauEmployéPanel;
    public static VisionnerEmployéPanel visionnerEmployéPanel;
    public static ModificationEmployéPanel modificationEmployéPanel;
    SuppressionEmployéPanel suppressionEmployéPanel;

    private static FrameEmployé myInstance;

    public static FrameEmployé getInstance() {
        if (myInstance == null) {
            myInstance = new FrameEmployé();
        }
        return myInstance;
    }

    /**
     * Creates new form FrameClient
     */
    public FrameEmployé() {
        initComponents();

        nouveauEmployéPanel = new NouveauEmployéPanel();
        visionnerEmployéPanel = new VisionnerEmployéPanel();
        modificationEmployéPanel = new ModificationEmployéPanel();
        suppressionEmployéPanel = new SuppressionEmployéPanel();
        DynamicPanel.setLayout(layout);

        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(nouveauEmployéPanel, c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(visionnerEmployéPanel, c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(modificationEmployéPanel, c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(suppressionEmployéPanel, c);
       
        afficherPanelNouveauEmployé();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarMenuPanel = new javax.swing.JPanel();
        btnNouveau = new javax.swing.JButton();
        btnVisionner = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Employé");
        setVisible(false);

        sideBarMenuPanel.setBackground(new java.awt.Color(153, 153, 255));

        btnNouveau.setBackground(new java.awt.Color(0, 153, 153));
        btnNouveau.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        btnNouveau.setText("Nouveau");
        btnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauActionPerformed(evt);
            }
        });

        btnVisionner.setBackground(new java.awt.Color(0, 153, 153));
        btnVisionner.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        btnVisionner.setText("Visionner");
        btnVisionner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisionnerActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jButton3.setText("Modifcation");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jButton1.setText("Suppression");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarMenuPanelLayout = new javax.swing.GroupLayout(sideBarMenuPanel);
        sideBarMenuPanel.setLayout(sideBarMenuPanelLayout);
        sideBarMenuPanelLayout.setHorizontalGroup(
            sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNouveau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sideBarMenuPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnVisionner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBarMenuPanelLayout.setVerticalGroup(
            sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarMenuPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnNouveau)
                .addGap(52, 52, 52)
                .addComponent(btnVisionner)
                .addGap(93, 93, 93)
                .addComponent(jButton3)
                .addGap(70, 70, 70)
                .addComponent(jButton1)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        getContentPane().add(sideBarMenuPanel, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauActionPerformed
        afficherPanelNouveauEmployé();
    }//GEN-LAST:event_btnNouveauActionPerformed

    private void btnVisionnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisionnerActionPerformed
        afficherPanelVisionnerEmployé();
    }//GEN-LAST:event_btnVisionnerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        afficherPanelModificationEmployé();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        afficherPanelSuppressionEmployé();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void afficherPanelNouveauEmployé() {
        nouveauEmployéPanel.setVisible(true);
        visionnerEmployéPanel.setVisible(false);
        modificationEmployéPanel.setVisible(false);
        suppressionEmployéPanel.setVisible(false);
       
    }

    public void afficherPanelVisionnerEmployé() {
        nouveauEmployéPanel.setVisible(false);
        visionnerEmployéPanel.setVisible(true);
        modificationEmployéPanel.setVisible(false);
        suppressionEmployéPanel.setVisible(false);
        
    }

    public void afficherPanelModificationEmployé() {
        nouveauEmployéPanel.setVisible(false);
        visionnerEmployéPanel.setVisible(false);
        modificationEmployéPanel.setVisible(true);
        suppressionEmployéPanel.setVisible(false);
        
    }

    public void afficherPanelSuppressionEmployé() {
        nouveauEmployéPanel.setVisible(false);
        visionnerEmployéPanel.setVisible(false);
        modificationEmployéPanel.setVisible(false);
        suppressionEmployéPanel.setVisible(true);
        
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton btnNouveau;
    private javax.swing.JButton btnVisionner;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel sideBarMenuPanel;
    // End of variables declaration//GEN-END:variables


}
