/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames.MyPanels;

import GestionBancaire.ConnectionBD;
import static MyFrames.MyPanels.VisionnerClientPanel.fillTable;
import static MyFrames.MyPanels.VisionnerClientPanel.model;
import gestionbancaire3.Authentification;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author asus pro
 */
public class ModificationClientPanel extends javax.swing.JPanel {
    
    int id_client;
    /**
     * Creates new form ModificationSuppressionClientPanel
     */
    public ModificationClientPanel() {
        initComponents();
        String requete;
         
        try {

            ConnectionBD conn = new ConnectionBD();
            ResultSet rs;
            if(Authentification.code_agence != 1)
            {
                requete = "select * from agences where code_agence=?";
                rs = conn.initRequetePreparee(requete, true,Authentification.code_agence).executeQuery();
            }
            else {
                requete = "select * from agences";
                rs = conn.Select(requete);
            }
             

            while(rs.next())
            {
                liste_agences.addItem(rs.getString("nom_agence"));
            }

            conn.disconnect();
        } catch (Exception e) {
            System.err.println(e);
        }
            
        if(Authentification.code_agence == 1)
        {
            liste_agences.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cin_field = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cin_modification = new javax.swing.JTextField();
        nom_modification = new javax.swing.JTextField();
        prenom_modification = new javax.swing.JTextField();
        btnModifier = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        liste_agences = new javax.swing.JComboBox<String>();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("CIN :");

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("CIN :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Nom :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Prenom :");

        btnModifier.setBackground(new java.awt.Color(255, 204, 153));
        btnModifier.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnModifier.setText("Modifier");
        btnModifier.setEnabled(false);
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Agence : ");

        liste_agences.setEnabled(false);
        liste_agences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liste_agencesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cin_modification)
                    .addComponent(prenom_modification)
                    .addComponent(liste_agences, 0, 181, Short.MAX_VALUE)
                    .addComponent(nom_modification)
                    .addComponent(cin_field))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cin_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cin_modification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nom_modification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenom_modification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(liste_agences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifier))
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String cin = cin_field.getText();
        
         try {
            ConnectionBD conn = new ConnectionBD();
            String sql = "select * from clients where cin_client=?";
            PreparedStatement preparedstm = conn.initRequetePreparee(sql, true, cin);
            ResultSet rs = preparedstm.executeQuery();
            
            if (rs.next()) {
                id_client = rs.getInt("id_client");
                cin_modification.setText(rs.getString("cin_client"));
                nom_modification.setText(rs.getString("nom_client"));
                prenom_modification.setText(rs.getString("prenom_client"));
                
                btnModifier.setEnabled(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "cin inexistant");
            }
            
            conn.disconnect();
        } catch (Exception e) {
            System.err.println(e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        
        String cin = cin_modification.getText();
        String nom = nom_modification.getText();
        String prenom = prenom_modification.getText();
        String nom_agence = liste_agences.getSelectedItem().toString();
        String get_code_agence_sql = "Select code_agence from agences where nom_agence= ?";

        String requete = "update clients set cin_client=?,nom_client=?,prenom_client=?,code_agence=? where id_client=?";
        try {
            ConnectionBD conn = new ConnectionBD();
            PreparedStatement preparedStm = conn.initRequetePreparee(get_code_agence_sql, true,nom_agence);
            ResultSet rs = preparedStm.executeQuery();
            if(rs.next())
            {
                preparedStm = conn.initRequetePreparee(requete, true, cin, nom, prenom,rs.getInt("code_agence"),id_client);
                preparedStm.executeUpdate();

                JOptionPane.showMessageDialog(null, "client modifié");

                //actualiser la table des clients
                VisionnerClientPanel.model.setRowCount(0);
                requete = "select code_agence from agences where nom_agence=?";
                 rs = conn.initRequetePreparee(requete, true, nom_agence).executeQuery();
                if (rs.next()) {
                    String sql = "select * from clients where code_agence=?;";
                    fillTable(sql, rs.getInt("code_agence"));

                }
                       
                 
            }
            
            conn.disconnect();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        btnModifier.setEnabled(false);
    }//GEN-LAST:event_btnModifierActionPerformed

    private void liste_agencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liste_agencesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liste_agencesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModifier;
    private javax.swing.JTextField cin_field;
    private javax.swing.JTextField cin_modification;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> liste_agences;
    private javax.swing.JTextField nom_modification;
    private javax.swing.JTextField prenom_modification;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getListe_agences() {
        return liste_agences;
    }
}
