/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames.MyPanels;

import GestionBancaire.ConnectionBD;
import static MyFrames.MyPanels.VisionnerClientPanel.fillTable;
import static MyFrames.MyPanels.VisionnerClientPanel.model;
import gestionbancaire3.Authentification;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author asus pro
 */
public class ModificationEmployéPanel extends javax.swing.JPanel {

    int id_emp;

    /**
     * Creates new form ModificationSuppressionClientPanel
     */
    public ModificationEmployéPanel() {
        initComponents();
        String requete;

        try {

            ConnectionBD conn = new ConnectionBD();
            ResultSet rs;
            if (Authentification.code_agence != 1) {
                requete = "select * from agences where code_agence=?";
                rs = conn.initRequetePreparee(requete, true, Authentification.code_agence).executeQuery();
            } else {
                requete = "select * from agences";
                rs = conn.Select(requete);
            }

            while (rs.next()) {
                liste_agences.addItem(rs.getString("nom_agence"));
            }

            conn.disconnect();
        } catch (Exception e) {
            System.err.println(e);
        }

        if (Authentification.code_agence == 1) {
            liste_agences.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ID_field = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ID_modification = new javax.swing.JTextField();
        nom_modification = new javax.swing.JTextField();
        prenom_modification = new javax.swing.JTextField();
        btnModifier = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        liste_agences = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        date_naissance_modification = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        poste_modification = new javax.swing.JTextField();
        login_modification = new javax.swing.JTextField();
        password_modification = new javax.swing.JPasswordField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("ID :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));
        add(ID_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 160, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("ID :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Nom :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Prenom :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        add(ID_modification, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 160, -1));
        add(nom_modification, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 160, -1));
        add(prenom_modification, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 160, -1));

        btnModifier.setBackground(new java.awt.Color(255, 204, 153));
        btnModifier.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnModifier.setText("Modifier");
        btnModifier.setEnabled(false);
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });
        add(btnModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 105, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Agence: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        liste_agences.setEnabled(false);
        liste_agences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liste_agencesActionPerformed(evt);
            }
        });
        add(liste_agences, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 160, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Date Naissance : ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));
        add(date_naissance_modification, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 160, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Poste :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Login :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Password :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));
        add(poste_modification, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 160, -1));
        add(login_modification, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 160, -1));
        add(password_modification, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String ID = ID_field.getText();

        try {
            ConnectionBD conn = new ConnectionBD();
            String sql = "select * from employes where id_emp=?";
            PreparedStatement preparedstm = conn.initRequetePreparee(sql, true, ID);
            ResultSet rs = preparedstm.executeQuery();

            if (rs.next()) {
                id_emp = rs.getInt("id_emp");
                ID_modification.setText(rs.getString("id_emp"));
                nom_modification.setText(rs.getString("nom_emp"));
                prenom_modification.setText(rs.getString("prenom_emp"));
                date_naissance_modification.setText(rs.getString("date_naissance_emp"));
                poste_modification.setText(rs.getString("poste"));
                login_modification.setText(rs.getString("login"));
                password_modification.setText(rs.getString("password"));
                btnModifier.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "ID inexistant");
            }

            conn.disconnect();
        } catch (Exception e) {
            System.err.println(e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed

        String ID = ID_modification.getText();
        String nom_emp = nom_modification.getText();
        String prenom_emp = prenom_modification.getText();
        String date_naissance_emp = date_naissance_modification.getText();
        String poste = poste_modification.getText();
        String login = login_modification.getText();
        String password = password_modification.getText();
        String nom_agence = liste_agences.getSelectedItem().toString();
        String get_id_agence_sql = "Select code_agence from agences where nom_agence= ?";

        String requete = "update employes set id_emp=?,nom_emp=?,prenom_emp=?,date_naissance_emp=?,poste=?,login=?,password=?"
                + ",code_agence=? where id_emp=?";
        try {
            ConnectionBD conn = new ConnectionBD();
            PreparedStatement preparedStm = conn.initRequetePreparee(get_id_agence_sql, true, nom_agence);
            ResultSet rs = preparedStm.executeQuery();
            if (rs.next()) {
                preparedStm = conn.initRequetePreparee(requete, true, ID, nom_emp, prenom_emp, date_naissance_emp,
                        poste, login, password, rs.getInt("code_agence"), id_emp);
                preparedStm.executeUpdate();

                JOptionPane.showMessageDialog(null, "Employé modifié");

                //actualiser la table des clients
                VisionnerClientPanel.model.setRowCount(0);
                requete = "select code_agence from agences where nom_agence=?";
                rs = conn.initRequetePreparee(requete, true, nom_agence).executeQuery();
                if (rs.next()) {
                    String sql = "select * from employes where code_agence=?;";
                    fillTable(sql, rs.getInt("code_agence"));

                }

            }

            conn.disconnect();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        btnModifier.setEnabled(false);
    }//GEN-LAST:event_btnModifierActionPerformed

    private void liste_agencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liste_agencesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liste_agencesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID_field;
    private javax.swing.JTextField ID_modification;
    private javax.swing.JButton btnModifier;
    private javax.swing.JTextField date_naissance_modification;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> liste_agences;
    private javax.swing.JTextField login_modification;
    private javax.swing.JTextField nom_modification;
    private javax.swing.JPasswordField password_modification;
    private javax.swing.JTextField poste_modification;
    private javax.swing.JTextField prenom_modification;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getListe_agences() {
        return liste_agences;
    }
}
